<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>EmpireSim</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../src/EmpireSim.Core/EmpireSim.Core.csproj" />
  </ItemGroup>

</Project>
